import { Radio_Canada, Geist_Mono } from "next/font/google";

import Nav from "./components/Navbar";
import LanguageSwitcher from "./components/LanguageSwitcher";
import Footer from "./components/Footer";

import { HeroUIProvider } from "@heroui/react";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import "../globals.css";

const radio = Radio_Canada({
  variable: "--font-radio-canada",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, params
}) {
  const { lng } = await params;

  if (!routing.locales.includes(lng)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={lng} dir='ltr'>
      <body className={`${radio.className}`}>
        <NextIntlClientProvider messages={messages}>
          <HeroUIProvider>
            <Nav lng={lng} />
            <LanguageSwitcher lng={lng} />
            {children}
            <Footer lng={lng} />
          </HeroUIProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
